"""
Gemini worksheet renderer — Canvas-style HTML generation.

Replaces the Python template_renderer for worksheets/quizzes/etc. while
preserving the 5-agent content pipeline upstream. The Content Agent still
writes grade-appropriate, standards-aligned question JSON via Claude Sonnet;
this module hands that JSON to Gemini 2.5 Pro (the same model behind
gemini.google.com's Canvas feature) along with the Pedagogy Brief, rubric,
and pre-rendered structured visuals, and asks for a polished self-contained
HTML document suitable for Carbone PDF rendering or direct browser preview.

Why Gemini 2.5 Pro: it's the model behind the Canvas UI in AI Studio, which
produces visibly more polished worksheet layouts than the fixed-template
renderer. Flash is available as a cheaper/faster alternative via env var.

Public API:
    render_worksheet_html(template_id, content_output, rubric_output,
                          pedagogy_brief=None, answer_key=False, theme=None) -> str
"""
import json
import logging
import os
from typing import Optional

log = logging.getLogger(__name__)

DEFAULT_MODEL = os.environ.get("GEMINI_WORKSHEET_MODEL", "gemini-2.5-pro")
MAX_OUTPUT_TOKENS = 32768  # worksheets can be 10-50KB of HTML

# ---------------------------------------------------------------------------
# Canvas-style system prompt
# ---------------------------------------------------------------------------
# Mirrors the instructions Gemini's Canvas UI uses to produce polished,
# print-ready documents. Key goals: self-contained HTML, inline CSS, semantic
# structure, careful typography, zero external dependencies.

_CANVAS_SYSTEM = """You are a worksheet designer producing polished, print-ready K-12 classroom materials.

Your output is a SINGLE self-contained HTML document — no external stylesheets, no external fonts, no external images, no JavaScript. Everything inline. The document must render identically in a browser and in a Carbone PDF pipeline.

Design principles you must follow every time:
1. Clean typography — system fonts only (system-ui, -apple-system, Segoe UI, Roboto), 11-13pt body, clear hierarchy.
2. Generous whitespace between questions; never cram.
3. Print-safe: use `@page { size: letter; margin: 0.5in; }` and `@media print` rules that hide screen-only chrome.
4. Question numbering is large and bold; answer space is visible (ruled lines, grid, box, whatever fits the question type).
5. Grade-appropriate visual weight. K-2 worksheets have larger fonts, thicker borders, rounder corners, friendlier colors. 9-12 worksheets are denser, cleaner, more academic.
6. Respect the Pedagogy Brief's visual directives literally (font sizes, color palette, scaffolding intensity).
7. Preserve the structured visuals exactly as provided — they are pre-rendered SVG. Do not modify the SVG markup; wrap it in a container if layout requires, but the inner SVG is authoritative.
8. When rendering an answer key, mark correct answers clearly (bold, highlighted, or with ✓) — the teacher version must be instantly graded against.
9. Include a simple header with: title, grade + subject + standards codes, optional space for student name + date.
10. Add a small footer credit "Generated by Lulia" on the last page only.

Output exactly one complete HTML document starting with <!DOCTYPE html> and ending with </html>. No commentary before or after. No markdown fences."""


def render_worksheet_html(
    template_id: str,
    content_output: dict,
    rubric_output: Optional[dict] = None,
    pedagogy_brief: Optional[str] = None,
    work_order: Optional[dict] = None,
    answer_key: bool = False,
    theme: Optional[str] = None,
    model: Optional[str] = None,
) -> str:
    """
    Render a worksheet (or any output template) to HTML via Gemini 2.5 Pro.

    The caller is responsible for having already run the content pipeline
    (Curriculum -> Pedagogy Director -> Content -> Rubric -> QA). This function
    only does the formatting step — same contract as the Python template_renderer.

    Args:
        template_id: one of the 22 template types (worksheet, quiz_test, task_cards...)
        content_output: Content Agent output with `questions` array
        rubric_output: Rubric Agent output with `answer_key` array (optional for student view)
        pedagogy_brief: Pedagogy Director brief text (grade-band visual constraints)
        work_order: original work order (grade, subject, standards, title)
        answer_key: if True, render the teacher version with answers visible
        theme: one of the 4 design themes (optional; Gemini picks appropriate colors)
        model: override default Gemini model

    Returns:
        Complete HTML document as a string.
    """
    # Pre-render any structured visuals in the questions so Gemini doesn't have
    # to re-invent ten_frames, number_bonds, fraction bars, etc. — those are
    # grade-appropriate SVG the visual_renderer already produces.
    questions = _prerender_visuals(content_output.get("questions", []))

    # Merge rubric answers into questions for answer-key view
    if answer_key and rubric_output and rubric_output.get("answer_key"):
        answer_by_num = {
            item.get("question_number"): item
            for item in rubric_output["answer_key"]
        }
        for q in questions:
            ak = answer_by_num.get(q.get("question_number"))
            if ak:
                q["correct_answer"] = ak.get("correct_answer")
                q["points"] = ak.get("points", 1)
                q["teacher_notes"] = ak.get("notes", "")

    wo = work_order or {}
    payload = {
        "template_id": template_id,
        "title": content_output.get("title") or wo.get("title") or "Worksheet",
        "grade_level": wo.get("grade_level") or content_output.get("grade_level"),
        "subject": wo.get("subject") or content_output.get("subject"),
        "standards": content_output.get("standards") or wo.get("standards") or [],
        "objective": content_output.get("objective") or wo.get("objective"),
        "questions": questions,
        "word_bank": content_output.get("word_bank"),
        "instructions": content_output.get("instructions"),
        "theme": theme or wo.get("design_theme") or "modern_clean",
        "answer_key": answer_key,
    }

    user_prompt = _build_prompt(payload, pedagogy_brief)

    html = _call_gemini(user_prompt, model)
    return _sanitize_html(html)


# ---------------------------------------------------------------------------
# Internals
# ---------------------------------------------------------------------------

def _prerender_visuals(questions: list) -> list:
    """
    Convert any structured `visual` objects into inline SVG via visual_renderer.
    Gemini then treats them as opaque HTML snippets to position in layout.
    """
    from src.lms_agents.tools.visual_renderer import render_visual

    out = []
    for q in questions:
        q_copy = dict(q)
        visual = q_copy.get("visual")
        if visual:
            svg = render_visual(visual)
            if svg:
                q_copy["visual_svg"] = svg
            # Keep original visual dict too in case Gemini wants context,
            # but the SVG is authoritative for rendering.
        out.append(q_copy)
    return out


def _build_prompt(payload: dict, pedagogy_brief: Optional[str]) -> str:
    """Build the user turn for Gemini — JSON payload + brief + Canvas framing."""
    template_id = payload["template_id"]
    answer_key = payload["answer_key"]
    mode_label = "ANSWER KEY (teacher version)" if answer_key else "STUDENT WORKSHEET"

    parts = [
        f"Produce a {mode_label} using the content below, formatted as a {template_id}.",
        "",
        f"Grade: {payload.get('grade_level', 'unspecified')}",
        f"Subject: {payload.get('subject', 'unspecified')}",
    ]
    standards = payload.get("standards") or []
    if standards:
        std_codes = [s.get("code") if isinstance(s, dict) else str(s) for s in standards]
        parts.append(f"Standards: {', '.join(std_codes[:5])}")
    if payload.get("objective"):
        parts.append(f"Objective: {payload['objective']}")
    parts.append("")

    if pedagogy_brief:
        parts.append("PEDAGOGY BRIEF (follow literally — these are developmental constraints):")
        parts.append(pedagogy_brief[:3000])  # keep prompt size sane
        parts.append("")

    parts.append("CONTENT JSON (render this as polished HTML):")
    parts.append("```json")
    parts.append(json.dumps({
        "title": payload["title"],
        "instructions": payload.get("instructions"),
        "word_bank": payload.get("word_bank"),
        "questions": payload["questions"],
    }, indent=2, default=str)[:40000])  # cap very large payloads
    parts.append("```")
    parts.append("")
    parts.append(
        "IMPORTANT: Any `visual_svg` field on a question is pre-rendered SVG — "
        "embed it verbatim in the question's answer area. Do not modify its markup."
    )
    if answer_key:
        parts.append(
            "This is the ANSWER KEY. Show the correct answer beside or below each question "
            "(bold, highlighted, or with a ✓). Include a small header noting 'Teacher Answer Key'."
        )
    else:
        parts.append(
            "This is the STUDENT worksheet. Do NOT show correct_answer or teacher_notes. "
            "Provide appropriate answer space (lines, boxes, grid) for each question type."
        )
    parts.append("")
    parts.append("Return ONE complete HTML document. Start with <!DOCTYPE html>. No preamble.")

    return "\n".join(parts)


def _call_gemini(user_prompt: str, model: Optional[str]) -> str:
    """Direct Gemini API call — no fallback (we want consistent Gemini quality)."""
    try:
        import google.generativeai as genai
    except ImportError as e:
        raise RuntimeError(f"google-generativeai not installed: {e}")

    api_key = os.environ.get("GOOGLE_GEMINI_API_KEY")
    if not api_key:
        raise RuntimeError("GOOGLE_GEMINI_API_KEY not set")

    genai.configure(api_key=api_key)
    gen_config = {
        "max_output_tokens": MAX_OUTPUT_TOKENS,
        "temperature": 0.4,
    }
    m = genai.GenerativeModel(
        model or DEFAULT_MODEL,
        system_instruction=_CANVAS_SYSTEM,
        generation_config=gen_config,
    )
    resp = m.generate_content(user_prompt)
    text = resp.text or ""
    if not text.strip():
        raise RuntimeError("Gemini returned empty worksheet HTML")
    return text


def _sanitize_html(raw: str) -> str:
    """Strip markdown fences if Gemini wrapped its output; trim whitespace."""
    import re
    raw = raw.strip()
    raw = re.sub(r"^```(?:html)?\s*\n?", "", raw)
    raw = re.sub(r"\n?```\s*$", "", raw)
    # If Gemini added a preamble before <!DOCTYPE, drop it
    idx = raw.lower().find("<!doctype")
    if idx > 0:
        raw = raw[idx:]
    return raw.strip()
